### PR TITLE
changed printer to sw-duplex

### PR DESCRIPTION
**Pull request by dheidemann**

### CODE REVIEW

**Review by christian-heusel — APPROVED** [review]
LGTM, altough I think changing this here has almost no effect 🤔

**Comment by christian-heusel** [comment]
> need help for next steps updating moozean 😄

The config for the live system is over at `cherry:/opt/docker/moozean/docker-moozean.env`, but I think further things are better discussed in an infra issue than here 😊

**Comment by dheidemann** [comment]
well, i searched for `sw-simplex` on cherry and obviously didnt find any printer var. Turns out it was `farbdruck-duplex`... Changed this now also on the live system

**Comment by christian-heusel** [comment]
@dheidemann did you also restart the related `moozean` docker container so that the change actually comes into effect?

**Comment by dheidemann** [comment]
doesnt work yet

**Comment by christian-heusel** [comment]
> doesnt work yet

Hmm?

**Pull request merged**
